### ISSUE TITLE
Documentation for JSON job syntax?

### ISSUE THREAD

**Issue by zamirkhan** [moviemasher/moviemasher.rb#10]
I'm interested in running moviemasher.rb without the js and angular components (give it jobs directly from a web app). So from what I can tell, I could either write some ruby on top of it (e.g. expose an API to my web app) to have it process jobs that way or preferably pass it JSON descriptions of jobs I want it to process. I can see the ruby syntax here: https://rawgit.com/moviemasher/moviemasher.rb/master/doc/index.html. However, I'm not sure where to find documentation or code that describes the proper JSON structure. Are there samples available without having to get the other projects up and running? Thanks.

**Comment by zamirkhan** [comment]
It looks like spec/helpers/media/JSON is a good spot for examples to peruse?

**Comment by syntropo** [comment]
You had found the full documentation of the JSON syntax for jobs and mashes embedded within them. That directory does contain snippets but they are turned into complete jobs as the spec tests run. There aren't actually any full job payloads in the project since they can be so easily created when running the system in Docker. This is really the best way to explore the format because it is clear what constructs are needed in the mash to produce particular outcomes in the editor/renderer. If you're not on board yet with Docker, the system can also be easily run in AWS though there are charges there for the resources consumed.

**Comment by zamirkhan** [comment]
Thanks for your help. Using the docker-compose command outlined in the angular-moviemasher, I was able to get a full system up and running locally and use the web ui to create my own mash. I was then able to get the corresponding mash outputs (json and mp4) from the containers. This is a great start. If I wanted to create syntactically correct job files, but without human interaction or a UI, would you recommend leveraging specific code from angular-moviemasher, moviemasher.js, or just rolling my own?

**Comment by syntropo** [comment]
I'm glad you were able to get the system running locally in Docker and also find what you needed in order to properly explore. I would thoroughly review apiutils.php since it does most of the job packaging, based on the options set in the moviemasher.ini file. And probably helpful to check out the callback scripts too, since they are looking for posted data as configured in the job.

**Comment by zamirkhan** [comment]
Thank you. I noticed in the JSON job file that each uploaded video in the mash had a FPS of '10' specified, even though they all had different initial frame rates. Are the videos transcoded during the upload process, is the FPS = 10 simply the video rate that they will have when the output result is created, or is there another option I'm not considering?

**Comment by syntropo** [comment]
An uploaded video is encoded into a folder full of JPEGs and an accompanying MP3 soundtrack. The `fps` value refers just to the frame rate of that image sequence, and is know in moviemasher.ini as `import_video_rate`. Neither has any bearing at all on the rendered video - the image sequence is used exclusively to display the preview within the UI. When rendering, we always use the original uploaded asset that is specified in the `source` property.

**Comment by zamirkhan** [comment]
Thanks for your response. That makes perfect sense. Although I'm sure I will have more questions as I delve deeper, I think you've given me quite enough to start with, so I will close this issue. Thanks again for creating and supporting moviemasher!
